name: "Callable workflow"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  callable:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.name }} from the callable workflow"
