name: "Download Artifact"

on:
  workflow_call:

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact-${{ github.sha }}
          path: artifact.zip

      - name: Extract Artifact
        # github zips the artifact on download, so we need
        # to unzip it first whether it's been compressed or not before uploading
        run: |
          unzip artifact.zip
          tar -xvf artifact.tar

      - name: List Files
        run: |
          ls -la artifact
