name: "Coin flip"

on:
  workflow_dispatch:
    inputs:
      dependent_job:
        required: true
        type: choice
        options:
          - Passing
          - Failing

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: "Something passing"
        if: ${{ github.event.inputs.dependent_job == 'Passing' }}
        run: echo "This job passes"
      - name: "Something failing"
        if: ${{ github.event.inputs.dependent_job == 'Failing' }}
        run: exit 1

  call_workflow:
    needs: process
    uses: ./.github/workflows/callable.yml
    with:
      name: "Coinflip"
