name: "Create PR artifact"

on:
  pull_request:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact
        run: |
          mkdir -p path/to/artifact 
          echo "Hello from ${{ github.event.pull_request.number }}" > path/to/artifact/hello.txt

      - name: "Tar files"
        run: tar -cvf artifact.tar path/to/artifact

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact-${{ github.event.pull_request.number }}
          path: artifact.tar

  call-workflow:
    needs: upload-artifact
    uses: ./.github/workflows/download-artifact.yml
